"""PDF audit reports (v0.5, issue #11).

Two pages, two audiences:

* **page 1 — synthèse dirigeant** : score, niveau, points saillants, recommandations.
  Written to be read by someone who will not open the technical annex.
* **page 2+ — annexe technique** : every finding, in the order it matters.

Implementation note — the issue suggested WeasyPrint or typst. Both need a native
rendering stack (pango/cairo, or a Rust binary) that must be installed in the image
and kept patched. :mod:`fpdf2` is pure Python: the report is generated by the same
``pip install -r requirements.txt`` that builds the rest of the API, in any
container, with no additional attack surface. The trade-off is a hand-written
layout instead of HTML/CSS, which for a two-page deterministic document is the
right side of the bargain.

Core PDF fonts are Latin-1 only, so every string is passed through
:func:`_safe` — otherwise a single em dash in an nmap detail (and there are many)
would abort the whole report.
"""

from datetime import datetime, timezone
from typing import Iterable, Optional, Sequence

from fpdf import FPDF

#: Severity order used for sorting and for the "top risks" selection.
SEVERITY_ORDER = ("critical", "high", "medium", "low", "info")
SEVERITY_LABELS = {
    "critical": "Critique",
    "high": "Élevée",
    "medium": "Moyenne",
    "low": "Faible",
    "info": "Information",
}
SEVERITY_WEIGHT = {"critical": 15, "high": 10, "medium": 5, "low": 2, "info": 0}

#: Characters outside Latin-1 that show up constantly in scan output.
_TRANSLITERATIONS = {
    "\u2014": "-",  # em dash
    "\u2013": "-",  # en dash
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2026": "...",
    "\u00a0": " ",
    "\u2022": "-",
}


def _safe(value: object) -> str:
    """Render any value as Latin-1 text a core PDF font can draw."""
    text = "" if value is None else str(value)
    for source, replacement in _TRANSLITERATIONS.items():
        text = text.replace(source, replacement)
    return text.encode("latin-1", "replace").decode("latin-1")


def risk_level(score: float) -> str:
    """Same thresholds as the interface, so the report never contradicts the UI."""
    if score >= 70:
        return "critique"
    if score >= 40:
        return "élevé"
    if score >= 20:
        return "modéré"
    if score > 0:
        return "faible"
    return "non évalué"


def _severity_rank(finding) -> int:
    severity = getattr(finding, "severity", "info")
    return SEVERITY_ORDER.index(severity) if severity in SEVERITY_ORDER else len(SEVERITY_ORDER)


def top_risks(findings: Sequence, limit: int = 5) -> list:
    """The findings a decision-maker should see first."""
    ordered = sorted(findings, key=lambda item: (_severity_rank(item), -getattr(item, "port", 0)))
    return list(ordered[:limit])


def recommendations(findings: Sequence) -> list[str]:
    """Turn the findings into actionable advice, in plain French.

    Deliberately rule-based and explainable: a recommendation an auditor cannot
    justify is worse than no recommendation at all.
    """
    advice: list[str] = []
    severities = {getattr(finding, "severity", "info") for finding in findings}
    sources = {getattr(finding, "source", "") for finding in findings}
    services = {str(getattr(finding, "service", "")).lower() for finding in findings}

    if "critical" in severities or "high" in severities:
        advice.append(
            "Traiter sans délai les constats de sévérité élevée ou critique : ils exposent "
            "directement le système d'information."
        )
    if "nvd" in sources or "nuclei" in sources:
        advice.append(
            "Appliquer les correctifs éditeurs associés aux vulnérabilités identifiées, "
            "puis relancer un scan de contrôle."
        )
    if services & {"telnet", "ftp", "rlogin", "rexec", "rsh"}:
        advice.append(
            "Remplacer ou désactiver les protocoles d'administration en clair observés "
            "(telnet, ftp, rlogin) au profit de SSH ou de HTTPS."
        )
    if services & {"microsoft-ds", "netbios-ssn", "smb"}:
        advice.append(
            "Restreindre l'exposition de SMB/NetBIOS au seul réseau d'administration."
        )
    if services & {"redis", "mongodb", "elasticsearch", "mysql", "postgresql"}:
        advice.append(
            "Vérifier que les services de bases de données ne sont pas joignables depuis "
            "un réseau non administré."
        )
    if not advice:
        advice.append(
            "Aucune action critique identifiée sur ce périmètre. Maintenir la surveillance "
            "et planifier un nouveau contrôle."
        )
    advice.append(
        "Conserver ce rapport comme pièce du dossier d'audit : il est horodaté et rattaché "
        "à une autorisation de test."
    )
    return advice


class _Report(FPDF):
    """Two-page report with a discreet footer on every page."""

    def __init__(self, target_name: str, scan_id: int, created_at: datetime) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.target_name = target_name
        self.scan_id = scan_id
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(16, 16, 16)

        # Metadata. The creation date is pinned to the caller's clock rather than
        # the wall clock, which makes the report **byte-for-byte reproducible**
        # from the same inputs: an audit artefact that changes on its own would be
        # worthless as evidence.
        self.set_creation_date(created_at)
        self.set_title(f"Rapport d'audit - {_safe(target_name)}")
        self.set_author("Sentinelle")
        self.set_subject(f"Scan #{scan_id} - diffusion restreinte")
        self.set_creator("Sentinelle")

    def header(self) -> None:
        self.set_font("helvetica", "B", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, _safe("SENTINELLE - RAPPORT D'AUDIT TECHNIQUE"), align="L")
        self.set_font("helvetica", "", 8)
        self.cell(0, 6, _safe(f"Cible : {self.target_name}"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("helvetica", "", 7)
        self.set_text_color(140, 140, 140)
        self.cell(0, 5, _safe(f"Scan #{self.scan_id} - diffusion restreinte - page {self.page_no()}"), align="C")
        self.set_text_color(0, 0, 0)

    def section_title(self, text: str) -> None:
        self.set_font("helvetica", "B", 12)
        self.cell(0, 8, _safe(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text: str) -> None:
        self.set_font("helvetica", "", 10)
        self.multi_cell(0, 5.5, _safe(text))
        self.ln(1)

    def bullet(self, text: str) -> None:
        self.set_font("helvetica", "", 10)
        self.set_x(self.l_margin)
        self.multi_cell(0, 5.5, _safe(f"- {text}"))
        self.ln(0.5)

    def label_value(self, label: str, value: str) -> None:
        self.set_font("helvetica", "B", 10)
        self.cell(45, 6, _safe(label))
        self.set_font("helvetica", "", 10)
        self.cell(0, 6, _safe(value), new_x="LMARGIN", new_y="NEXT")


def build_scan_report(
    scan,
    target,
    findings: Iterable,
    *,
    generated_by: Optional[str] = None,
    generated_at: Optional[datetime] = None,
) -> bytes:
    """Render a scan report as PDF bytes."""
    findings = list(findings)
    moment = generated_at or datetime.now(timezone.utc)
    score = float(getattr(scan, "risk_score", 0.0) or 0.0)
    severities = [getattr(finding, "severity", "info") for finding in findings]
    counts = {severity: severities.count(severity) for severity in SEVERITY_ORDER}

    pdf = _Report(target_name=target.name, scan_id=scan.id or 0, created_at=moment)
    pdf.add_page()

    # --- synthesis --------------------------------------------------------- #
    pdf.set_font("helvetica", "B", 18)
    pdf.multi_cell(0, 9, _safe("Rapport d'audit de sécurité"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(90, 90, 90)
    pdf.multi_cell(
        0,
        6,
        _safe(f"Synthèse dirigeant - {target.name}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    pdf.section_title("Périmètre et contexte")
    pdf.label_value("Cible :", f"{target.value} ({target.kind})")
    pdf.label_value("Autorisation :", target.authorization_reference or "périmètre interne autorisé")
    pdf.label_value("Statut :", str(getattr(scan, "status", "")).upper())
    pdf.label_value("Profil du scan :", "complet" if getattr(scan, "profile", "") == "full" else "rapide")
    pdf.label_value(
        "Exécuté le :",
        (scan.finished_at or scan.created_at).strftime("%d/%m/%Y à %H:%M UTC"),
    )
    pdf.label_value("Rapport généré le :", moment.strftime("%d/%m/%Y à %H:%M UTC"))
    if generated_by:
        pdf.label_value("Généré par :", generated_by)
    pdf.ln(3)

    pdf.section_title("Niveau de risque")
    pdf.body_text(
        f"Score global : {score:.0f}/100 — niveau {risk_level(score)}. "
        f"{len(findings)} constat(s) retenu(s) sur ce périmètre."
    )
    if any(counts.values()):
        breakdown = ", ".join(
            f"{SEVERITY_LABELS[severity]} {counts[severity]}"
            for severity in SEVERITY_ORDER
            if counts[severity]
        )
        pdf.body_text(f"Répartition : {breakdown}.")
    else:
        pdf.body_text("Aucun constat de vulnérabilité identifié.")

    pdf.ln(1)
    pdf.section_title("Points saillants")
    highlights = top_risks(findings)
    if not highlights:
        pdf.body_text("Aucun constat de vulnérabilité identifié sur ce périmètre.")
    else:
        for finding in highlights:
            label = SEVERITY_LABELS.get(getattr(finding, "severity", "info"), "Information")
            location = (
                f"port {finding.port}/{finding.protocol}"
                if getattr(finding, "port", 0)
                else getattr(finding, "service", "") or "constat applicatif"
            )
            pdf.bullet(f"[{label}] {location} — {getattr(finding, 'detail', '')}".strip())

    pdf.ln(1)
    pdf.section_title("Recommandations")
    for advice in recommendations(findings):
        pdf.bullet(advice)

    # --- technical annex --------------------------------------------------- #
    pdf.add_page()
    pdf.section_title("Annexe technique - constats détaillés")
    pdf.set_font("helvetica", "", 9)
    pdf.body_text(
        "Tableau exhaustif des constats, triés par sévérité décroissante. "
        "La colonne « source » indique l'outil à l'origine du constat."
    )

    columns = (("source", 20), ("port", 14), ("service", 38), ("sev.", 20), ("détail", 86))
    pdf.set_font("helvetica", "B", 8)
    pdf.set_fill_color(238, 242, 247)
    for title, width in columns:
        pdf.cell(width, 6, _safe(title), border="B", fill=True)
    pdf.ln(6)

    pdf.set_font("helvetica", "", 8)
    ordered = sorted(findings, key=_severity_rank)
    if not ordered:
        pdf.cell(0, 6, _safe("Aucun constat."), new_x="LMARGIN", new_y="NEXT")
    for finding in ordered:
        detail = _safe(getattr(finding, "detail", ""))
        row = [
            _safe(getattr(finding, "source", "")),
            _safe(getattr(finding, "port", 0) or "-"),
            _safe((getattr(finding, "service", "") or "-")[:28]),
            _safe(SEVERITY_LABELS.get(getattr(finding, "severity", "info"), "Info")[:9]),
            detail,
        ]
        # A finding's detail can be long: keep it on the row, wrapped.
        line_height = 4.4
        wrapped = pdf.multi_cell(columns[-1][1], line_height, row[-1], split_only=True)
        needed = max(1, len(wrapped)) * line_height
        if pdf.get_y() + needed > pdf.h - pdf.b_margin:
            pdf.add_page()
            pdf.set_font("helvetica", "B", 8)
            for title, width in columns:
                pdf.cell(width, 6, _safe(title), border="B", fill=True)
            pdf.ln(6)
            pdf.set_font("helvetica", "", 8)

        top = pdf.get_y()
        for (_, width), value in zip(columns[:-1], row[:-1]):
            pdf.cell(width, line_height, value, border="B")
        x, y = pdf.get_x(), pdf.get_y()
        pdf.multi_cell(columns[-1][1], line_height, row[-1], border="B")
        pdf.set_xy(pdf.l_margin, max(pdf.get_y(), top + needed))

    output = pdf.output()
    return bytes(output)
