"""v0.5 governance — organizations, tenancy columns, audit trail

Revision ID: 0004_governance
Revises: 0003_intel
Create Date: 2026-09-21

Migration for the v0.5 "Rapports & gouvernance" milestone (issues #13, #15):

  * ``organizations`` — the tenant boundary, with row ``id = 1`` created by this
    revision as the **default organization**.
  * ``org_id`` added to ``users``, ``targets``, ``scans``, ``findings`` and
    ``alerts``, existing rows backfilled into organization 1. Alerts are the one
    nullable case: ``NULL`` means *platform-wide* (the sensor feed and threat-intel
    matches belong to the platform, not to a customer).
  * ``audit_logs`` — the append-only "who did what, when" trail.
  * ``users.sso_subject`` — link to an external identity (issue #14).

The tenancy columns keep a ``server_default`` of ``1``. That is deliberate: it
makes a legacy insert (a script, a migration, an operator with psql open) land in
the default organization instead of failing or, worse, creating an orphan row.
``alembic check`` ignores server defaults, so the schema stays aligned with the
models.

Written by hand rather than autogenerated: a generated ``NOT NULL`` column
without a default cannot be applied to a table that already has rows.
"""

from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_governance"
down_revision: Union[str, None] = "0003_intel"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_ORG_ID = 1
TENANT_TABLES = ("targets", "scans", "findings")


def upgrade() -> None:
    # --- 1. the tenant table, and its default row -------------------------- #
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # timezone=True from the start: this row is inserted *below*, and
        # PostgreSQL/asyncpg refuses an aware datetime for a naive column. The
        # bulk conversion happens in 0005, which is too late for this insert.
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_organizations_slug", "organizations", ["slug"], unique=True)

    organizations = sa.table(
        "organizations",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("created_at", sa.DateTime),
    )
    op.bulk_insert(
        organizations,
        [
            {
                "id": DEFAULT_ORG_ID,
                "name": "Organisation par défaut",
                "slug": "default",
                # A real aware UTC datetime, not SQL now(): SQLite refuses
                # anything that is not a Python date/datetime object, and the
                # column is timestamptz so PostgreSQL accepts the offset.
                "created_at": datetime.now(timezone.utc),
            }
        ],
    )

    # --- 2. tenancy on users, plus the SSO link --------------------------- #
    with op.batch_alter_table("users") as batch:
        batch.add_column(
            sa.Column("org_id", sa.Integer(), nullable=False, server_default=str(DEFAULT_ORG_ID))
        )
        batch.add_column(sa.Column("sso_subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch.create_foreign_key("fk_users_org_id", "organizations", ["org_id"], ["id"])
    op.create_index("ix_users_org_id", "users", ["org_id"], unique=False)
    op.create_index("ix_users_sso_subject", "users", ["sso_subject"], unique=False)

    # --- 3. tenancy on the scan chain ------------------------------------- #
    for table in TENANT_TABLES:
        with op.batch_alter_table(table) as batch:
            batch.add_column(
                sa.Column("org_id", sa.Integer(), nullable=False, server_default=str(DEFAULT_ORG_ID))
            )
            batch.create_foreign_key(f"fk_{table}_org_id", "organizations", ["org_id"], ["id"])
        op.create_index(f"ix_{table}_org_id", table, ["org_id"], unique=False)

    # --- 4. alerts: nullable on purpose (NULL = platform-wide) ------------- #
    with op.batch_alter_table("alerts") as batch:
        batch.add_column(sa.Column("org_id", sa.Integer(), nullable=True))
        batch.create_foreign_key("fk_alerts_org_id", "organizations", ["org_id"], ["id"])
    op.create_index("ix_alerts_org_id", "alerts", ["org_id"], unique=False)

    # --- 5. the audit trail ------------------------------------------------ #
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ("created_at", "actor_id", "actor_email", "org_id", "action", "entity", "entity_id", "ip"):
        op.create_index(f"ix_audit_logs_{column}", "audit_logs", [column], unique=False)


def downgrade() -> None:
    for column in ("created_at", "actor_id", "actor_email", "org_id", "action", "entity", "entity_id", "ip"):
        op.drop_index(f"ix_audit_logs_{column}", table_name="audit_logs")
    op.drop_table("audit_logs")

    op.drop_index("ix_alerts_org_id", table_name="alerts")
    with op.batch_alter_table("alerts") as batch:
        batch.drop_constraint("fk_alerts_org_id", type_="foreignkey")
        batch.drop_column("org_id")

    for table in TENANT_TABLES:
        op.drop_index(f"ix_{table}_org_id", table_name=table)
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(f"fk_{table}_org_id", type_="foreignkey")
            batch.drop_column("org_id")

    op.drop_index("ix_users_sso_subject", table_name="users")
    op.drop_index("ix_users_org_id", table_name="users")
    with op.batch_alter_table("users") as batch:
        batch.drop_constraint("fk_users_org_id", type_="foreignkey")
        batch.drop_column("sso_subject")
        batch.drop_column("org_id")

    op.drop_index("ix_organizations_slug", table_name="organizations")
    op.drop_table("organizations")
